# Setup
title:               Delta Intelligence
tagline:             'Advancing Multi-Agent and Continual Learning for LLMs'
description:         'Delta Intelligence advances multi-agent and continual learning for large language models (LLMs) in complex, interactive environments. Our goal is to enable LLMs to collaborate with humans and AI agents on long-horizon tasks.'
url:                 https://delta-intelligence-ai.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Delta Intelligence
  url:               https://github.com/Delta-Intelligence-AI
  email:             deltaintelligence@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
